import { afterAll, expect, test } from 'bun:test';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { sha256 } from '../digest.js';
import { parseThemeManifest } from '../schema.js';

/**
 * The CLI is driven as a subprocess, not by calling `main`.
 *
 * `cli.ts` ends in `process.exit`, so importing it would take the test runner
 * down with it. Running it the way a user runs it also makes the exit status a
 * tested property rather than an assumed one, and exit status is the entire
 * contract for anyone putting `muqun-theme validate` in a CI job.
 */
const CLI = new URL('../cli.ts', import.meta.url).pathname;
const roots: string[] = [];

function scratch(): string {
  const dir = mkdtempSync(join(tmpdir(), 'muqun-theme-cli-'));
  roots.push(dir);
  return dir;
}

afterAll(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

function run(...args: string[]): { code: number; stdout: string; stderr: string } {
  const result = Bun.spawnSync(['bun', CLI, ...args], {
    // NO_COLOR keeps the assertions about text, not about escape codes.
    env: { ...process.env, NO_COLOR: '1' },
  });
  return {
    code: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

test('help is the default, succeeds, and names every command', () => {
  // Asserts the behaviour rather than the layout: the help text is generated by
  // the CLI framework now, so pinning its exact spacing would make a cosmetic
  // upgrade look like a regression.
  for (const args of [[], ['help'], ['--help']]) {
    const result = run(...args);
    expect(result.code).toBe(0);
    expect(result.stdout).toContain('muqun-theme');
    for (const command of ['init', 'validate', 'contrast', 'pack', 'unpack'])
      expect(result.stdout).toContain(command);
  }
  // An unknown command still prints usage, but must not claim success.
  expect(run('frobnicate').code).toBe(1);
});

test('every command has its own help, and asking for it is not an error', () => {
  for (const command of ['init', 'validate', 'contrast', 'pack', 'unpack']) {
    const result = run(command, '--help');
    expect(result.code).toBe(0);
    expect(result.stdout.length).toBeGreaterThan(0);
  }
});

test('init writes a theme that validates and never fails at full opacity', () => {
  const dir = scratch();
  expect(run('init', '--dir', dir).code).toBe(0);

  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.id).toBe('my-theme');

  const validated = run('validate', dir);
  expect(validated.code).toBe(0);
  expect(validated.stdout).toContain('valid');

  const contrast = run('contrast', dir);
  expect(contrast.code).toBe(0);
  expect(contrast.stdout).not.toContain('fails at full opacity');
});

test('init scaffolds a complete theme that packs and installs unedited', () => {
  const dir = scratch();
  const result = run('init', 'grand-voyage', '--dir', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).toContain('placeholder images');

  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.decoration).toBeDefined();
  expect(manifest.icons).toBeDefined();
  expect(manifest.homeIdentity).toBeDefined();

  // Every declared asset exists on disk, which is what makes the scaffold
  // packable without an author finding a file first.
  for (const asset of Object.values(manifest.assets ?? {})) {
    if ('path' in asset) expect(existsSync(join(dir, asset.path))).toBe(true);
  }

  // The whole loop, on output nobody has edited.
  expect(run('validate', dir).code).toBe(0);
  expect(run('contrast', dir).code).toBe(0);
  const pack = join(scratch(), 'gv.muqun-theme');
  expect(run('pack', dir, '--out', pack).code).toBe(0);
  expect(run('validate', pack).code).toBe(0);
});

test('init warns that scaffolded artwork is still placeholder', () => {
  const dir = scratch();
  run('init', '--dir', dir);
  const result = run('validate', dir);
  expect(result.code).toBe(0); // a warning, never a failure
  expect(result.stdout).toContain('placeholder');
});

test('init --colors-only writes a palette and no assets', () => {
  const dir = scratch();
  expect(run('init', '--colors-only', '--dir', dir).code).toBe(0);
  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.assets).toBeUndefined();
  expect(manifest.decoration).toBeUndefined();

  const result = run('validate', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).not.toContain('placeholder');
});

test('init accepts a slug and the result still validates', () => {
  const dir = scratch();
  expect(run('init', 'grand-voyage', '--dir', dir).code).toBe(0);
  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.id).toBe('grand-voyage');
  expect(manifest.name).toBe('grand-voyage');
  expect(run('validate', dir).code).toBe(0);
});

test('pack optimises artwork to WebP, and the cycle still closes', () => {
  const source = scratch();
  run('init', 'voyage', '--dir', source);
  const pack = join(scratch(), 'voyage.muqun-theme');

  const packed = run('pack', source, '--out', pack);
  expect(packed.code).toBe(0);
  expect(packed.stdout).toContain('round trip ok');
  expect(packed.stdout).toContain('image(s) optimised');

  expect(run('validate', pack).code).toBe(0);

  const target = scratch();
  expect(run('unpack', pack, '--out', target).code).toBe(0);

  const before = parseThemeManifest(readFileSync(join(source, 'theme.json'), 'utf8'));
  const after = parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8'));

  // The paths move, because the artwork genuinely changed format. Everything
  // else about the theme must be untouched by packing it.
  for (const asset of Object.values(after.assets ?? {}))
    if ('path' in asset) expect(asset.path).toMatch(/\.webp$/);
  expect({ ...after, assets: undefined }).toEqual({ ...before, assets: undefined });
  expect(Object.keys(after.assets ?? {}).sort()).toEqual(Object.keys(before.assets ?? {}).sort());
});

test('pack --no-optimize reproduces the source theme exactly', () => {
  const source = scratch();
  run('init', 'voyage', '--dir', source);
  const pack = join(scratch(), 'voyage.muqun-theme');

  const packed = run('pack', source, '--out', pack, '--no-optimize');
  expect(packed.code).toBe(0);
  expect(packed.stdout).not.toContain('image(s) optimised');

  const target = scratch();
  expect(run('unpack', pack, '--out', target).code).toBe(0);

  // With optimisation off, the cycle is byte-for-byte: this is the guarantee an
  // author relies on when they want their exact artwork preserved.
  const before = parseThemeManifest(readFileSync(join(source, 'theme.json'), 'utf8'));
  const after = parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8'));
  expect(after).toEqual(before);
  for (const [id, asset] of Object.entries(before.assets ?? {})) {
    if (!('path' in asset)) continue;
    expect(readFileSync(join(target, asset.path))).toEqual(readFileSync(join(source, asset.path)));
    expect(id).toBeTruthy();
  }
});

test('unpack accepts a positional directory as well as --out', () => {
  const source = scratch();
  run('init', '--dir', source);
  const pack = join(scratch(), 'a.muqun-theme');
  run('pack', source, '--out', pack);
  const target = scratch();
  expect(run('unpack', pack, target).code).toBe(0);
  expect(parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8')).id).toBe('my-theme');
});

test('validate fails, with a usable message, on a manifest the app would refuse', () => {
  const dir = scratch();
  run('init', '--dir', dir);
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  manifest.variants.light.colors.text = 'not-a-color';
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));

  const result = run('validate', dir);
  expect(result.code).toBe(1);
  // The path of the offending value is what makes this actionable.
  expect(result.stderr).toContain('text');
});

test('validate reports a declared checksum that does not describe the file', () => {
  const dir = scratch();
  // Colours only: this test owns the whole asset table, and the full scaffold
  // wires icons and Home identity to assets it would be replacing.
  run('init', '--dir', dir, '--colors-only');
  const png = Uint8Array.from(
    Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
      'base64'
    )
  );
  writeFileSync(join(dir, 'assets', 'paper.png'), png);
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  manifest.assets = { paper: { path: 'assets/paper.png', sha256: 'f'.repeat(64) } };
  manifest.decoration = { 'shell.background': { asset: 'paper' } };
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));

  const failed = run('validate', dir);
  expect(failed.code).toBe(1);
  expect(failed.stdout).toContain('assets.paper.sha256');
  // pack refuses for the same reason rather than producing a pack that lies.
  expect(run('pack', dir, '--out', join(scratch(), 'x.muqun-theme')).code).toBe(1);

  manifest.assets.paper.sha256 = sha256(png);
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));
  expect(run('validate', dir).code).toBe(0);
});

test('a missing target is an error, not a stack trace', () => {
  const result = run('validate', join(scratch(), 'nowhere.muqun-theme'));
  expect(result.code).toBe(1);
  expect(result.stderr).toContain('No such file or directory');
  expect(result.stderr).not.toContain('at Object.');
});

test('warnings alone never fail a command', () => {
  const dir = scratch();
  run('init', '--dir', dir, '--colors-only');
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  // An unknown glyph name is deliberately tolerated, so that an older app
  // ignores a newer pack's icon instead of refusing the whole theme.
  manifest.assets = { crest: { path: 'assets/crest.png' } };
  manifest.icons = { 'chrome.teleport': { asset: 'crest', render: 'template' } };
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));
  writeFileSync(
    join(dir, 'assets', 'crest.png'),
    Uint8Array.from(
      Buffer.from(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
        'base64'
      )
    )
  );

  const result = run('validate', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).toContain('warning');
  expect(result.stdout).toContain('chrome.teleport');
});
