import { afterAll, expect, test } from 'bun:test';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { sha256 } from '../digest.js';
import { parseThemeManifest } from '../schema.js';

/**
 * The CLI is driven as a subprocess, not by calling `main`.
 *
 * `cli.ts` ends in `process.exit`, so importing it would take the test runner
 * down with it. Running it the way a user runs it also makes the exit status a
 * tested property rather than an assumed one, and exit status is the entire
 * contract for anyone putting `muqun-theme validate` in a CI job.
 */
const CLI = new URL('../cli.ts', import.meta.url).pathname;
const roots: string[] = [];

function scratch(): string {
  const dir = mkdtempSync(join(tmpdir(), 'muqun-theme-cli-'));
  roots.push(dir);
  return dir;
}

afterAll(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

function run(...args: string[]): { code: number; stdout: string; stderr: string } {
  const result = Bun.spawnSync(['bun', CLI, ...args], {
    // NO_COLOR keeps the assertions about text, not about escape codes.
    env: { ...process.env, NO_COLOR: '1' },
  });
  return {
    code: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

const COMMANDS = ['init', 'validate', 'contrast', 'pack', 'unpack', 'check', 'build', 'index', 'list', 'skill'];

test('help is the default, succeeds, and names every command', () => {
  // Asserts the behaviour rather than the layout: the help text is generated by
  // the CLI framework now, so pinning its exact spacing would make a cosmetic
  // upgrade look like a regression.
  for (const args of [[], ['help'], ['--help']]) {
    const result = run(...args);
    expect(result.code).toBe(0);
    expect(result.stdout).toContain('muqun-theme');
    for (const command of COMMANDS) expect(result.stdout).toContain(command);
  }
  // An unknown command still prints usage, but must not claim success.
  expect(run('frobnicate').code).toBe(1);
});

test('every command has its own help, and asking for it is not an error', () => {
  for (const command of COMMANDS) {
    const result = run(command, '--help');
    expect(result.code).toBe(0);
    expect(result.stdout.length).toBeGreaterThan(0);
  }
});

test('init writes a theme that validates and never fails at full opacity', () => {
  const dir = scratch();
  expect(run('init', '--dir', dir).code).toBe(0);

  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.id).toBe('my-theme');

  const validated = run('validate', dir);
  expect(validated.code).toBe(0);
  expect(validated.stdout).toContain('valid');

  const contrast = run('contrast', dir);
  expect(contrast.code).toBe(0);
  expect(contrast.stdout).not.toContain('fails at full opacity');
});

test('init scaffolds a complete theme that packs and installs unedited', () => {
  const dir = scratch();
  const result = run('init', 'grand-voyage', '--dir', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).toContain('placeholder images');

  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.decoration).toBeDefined();
  expect(manifest.icons).toBeDefined();
  expect(manifest.homeIdentity).toBeDefined();

  // Every declared asset exists on disk, which is what makes the scaffold
  // packable without an author finding a file first.
  for (const asset of Object.values(manifest.assets ?? {})) {
    if ('path' in asset) expect(existsSync(join(dir, asset.path))).toBe(true);
  }

  // The whole loop, on output nobody has edited.
  expect(run('validate', dir).code).toBe(0);
  expect(run('contrast', dir).code).toBe(0);
  const pack = join(scratch(), 'gv.muqun-theme');
  expect(run('pack', dir, '--out', pack).code).toBe(0);
  expect(run('validate', pack).code).toBe(0);
});

test('init warns that scaffolded artwork is still placeholder', () => {
  const dir = scratch();
  run('init', '--dir', dir);
  const result = run('validate', dir);
  expect(result.code).toBe(0); // a warning, never a failure
  expect(result.stdout).toContain('placeholder');
});

test('init --colors-only writes a palette and no assets', () => {
  const dir = scratch();
  expect(run('init', '--colors-only', '--dir', dir).code).toBe(0);
  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.assets).toBeUndefined();
  expect(manifest.decoration).toBeUndefined();

  const result = run('validate', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).not.toContain('placeholder');
});

test('init accepts a slug and the result still validates', () => {
  const dir = scratch();
  expect(run('init', 'grand-voyage', '--dir', dir).code).toBe(0);
  const manifest = parseThemeManifest(readFileSync(join(dir, 'theme.json'), 'utf8'));
  expect(manifest.id).toBe('grand-voyage');
  expect(manifest.name).toBe('grand-voyage');
  expect(run('validate', dir).code).toBe(0);
});

test('pack optimises artwork to WebP, and the cycle still closes', () => {
  const source = scratch();
  run('init', 'voyage', '--dir', source);
  const pack = join(scratch(), 'voyage.muqun-theme');

  const packed = run('pack', source, '--out', pack);
  expect(packed.code).toBe(0);
  expect(packed.stdout).toContain('round trip ok');
  expect(packed.stdout).toContain('image(s) optimised');

  expect(run('validate', pack).code).toBe(0);

  const target = scratch();
  expect(run('unpack', pack, '--out', target).code).toBe(0);

  const before = parseThemeManifest(readFileSync(join(source, 'theme.json'), 'utf8'));
  const after = parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8'));

  // The paths move, because the artwork genuinely changed format. Everything
  // else about the theme must be untouched by packing it.
  for (const asset of Object.values(after.assets ?? {}))
    if ('path' in asset) expect(asset.path).toMatch(/\.webp$/);
  expect({ ...after, assets: undefined }).toEqual({ ...before, assets: undefined });
  expect(Object.keys(after.assets ?? {}).sort()).toEqual(Object.keys(before.assets ?? {}).sort());
});

test('pack --no-optimize reproduces the source theme exactly', () => {
  const source = scratch();
  run('init', 'voyage', '--dir', source);
  const pack = join(scratch(), 'voyage.muqun-theme');

  const packed = run('pack', source, '--out', pack, '--no-optimize');
  expect(packed.code).toBe(0);
  expect(packed.stdout).not.toContain('image(s) optimised');

  const target = scratch();
  expect(run('unpack', pack, '--out', target).code).toBe(0);

  // With optimisation off, the cycle is byte-for-byte: this is the guarantee an
  // author relies on when they want their exact artwork preserved.
  const before = parseThemeManifest(readFileSync(join(source, 'theme.json'), 'utf8'));
  const after = parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8'));
  expect(after).toEqual(before);
  for (const [id, asset] of Object.entries(before.assets ?? {})) {
    if (!('path' in asset)) continue;
    expect(readFileSync(join(target, asset.path))).toEqual(readFileSync(join(source, asset.path)));
    expect(id).toBeTruthy();
  }
});

test('unpack accepts a positional directory as well as --out', () => {
  const source = scratch();
  run('init', '--dir', source);
  const pack = join(scratch(), 'a.muqun-theme');
  run('pack', source, '--out', pack);
  const target = scratch();
  expect(run('unpack', pack, target).code).toBe(0);
  expect(parseThemeManifest(readFileSync(join(target, 'theme.json'), 'utf8')).id).toBe('my-theme');
});

test('validate fails, with a usable message, on a manifest the app would refuse', () => {
  const dir = scratch();
  run('init', '--dir', dir);
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  manifest.variants.light.colors.text = 'not-a-color';
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));

  const result = run('validate', dir);
  expect(result.code).toBe(1);
  // The path of the offending value is what makes this actionable.
  expect(result.stderr).toContain('text');
});

test('validate reports a declared checksum that does not describe the file', () => {
  const dir = scratch();
  // Colours only: this test owns the whole asset table, and the full scaffold
  // wires icons and Home identity to assets it would be replacing.
  run('init', '--dir', dir, '--colors-only');
  const png = Uint8Array.from(
    Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
      'base64'
    )
  );
  writeFileSync(join(dir, 'assets', 'paper.png'), png);
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  manifest.assets = { paper: { path: 'assets/paper.png', sha256: 'f'.repeat(64) } };
  manifest.decoration = { 'shell.background': { asset: 'paper' } };
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));

  const failed = run('validate', dir);
  expect(failed.code).toBe(1);
  expect(failed.stdout).toContain('assets.paper.sha256');
  // pack refuses for the same reason rather than producing a pack that lies.
  expect(run('pack', dir, '--out', join(scratch(), 'x.muqun-theme')).code).toBe(1);

  manifest.assets.paper.sha256 = sha256(png);
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));
  expect(run('validate', dir).code).toBe(0);
});

test('a missing target is an error, not a stack trace', () => {
  const result = run('validate', join(scratch(), 'nowhere.muqun-theme'));
  expect(result.code).toBe(1);
  expect(result.stderr).toContain('No such file or directory');
  expect(result.stderr).not.toContain('at Object.');
});

test('warnings alone never fail a command', () => {
  const dir = scratch();
  run('init', '--dir', dir, '--colors-only');
  const manifest = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8'));
  // An unknown glyph name is deliberately tolerated, so that an older app
  // ignores a newer pack's icon instead of refusing the whole theme.
  manifest.assets = { crest: { path: 'assets/crest.png' } };
  manifest.icons = { 'chrome.teleport': { asset: 'crest', render: 'template' } };
  writeFileSync(join(dir, 'theme.json'), JSON.stringify(manifest));
  writeFileSync(
    join(dir, 'assets', 'crest.png'),
    Uint8Array.from(
      Buffer.from(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
        'base64'
      )
    )
  );

  const result = run('validate', dir);
  expect(result.code).toBe(0);
  expect(result.stdout).toContain('warning');
  expect(result.stdout).toContain('chrome.teleport');
});

/** The CLI run from inside a directory, the way an author in a repository runs it. */
function runIn(cwd: string, ...args: string[]): { code: number; stdout: string; stderr: string } {
  const result = Bun.spawnSync(['bun', CLI, ...args], {
    cwd,
    env: { ...process.env, NO_COLOR: '1' },
  });
  return {
    code: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

const SKILL_FILE = new URL('../../skills/muqun-theme/SKILL.md', import.meta.url).pathname;

test('inside a themes repository, init and pack default into src/ and dist/, and check holds them to it', () => {
  const repo = scratch();
  mkdirSync(join(repo, 'src'));
  mkdirSync(join(repo, 'dist'));

  // A repository needs its catalogue even when it is empty.
  const uncatalogued = runIn(repo, 'check');
  expect(uncatalogued.code).toBe(1);
  expect(uncatalogued.stdout).toContain('index.json is missing');
  expect(runIn(repo, 'index').stdout).toContain('wrote index.json (0 theme(s))');
  expect(JSON.parse(readFileSync(join(repo, 'index.json'), 'utf8'))).toEqual({
    format: 'muqun-themes-index',
    themes: [],
  });

  // Nothing yet is a passing state, not an error.
  const empty = runIn(repo, 'check');
  expect(empty.code).toBe(0);
  expect(empty.stdout).toContain('no themes yet');

  const init = runIn(repo, 'init', 'grand-voyage');
  expect(init.code).toBe(0);
  expect(init.stdout).toContain('src/grand-voyage/theme.json');
  expect(existsSync(join(repo, 'src', 'grand-voyage', 'theme.json'))).toBe(true);

  // A default location never overwrites a theme that is already there.
  const again = runIn(repo, 'init', 'grand-voyage');
  expect(again.code).toBe(1);
  expect(again.stderr).toContain('already holds a theme.json');

  // A source without its package fails, and the message says how to fix it.
  const unpacked = runIn(repo, 'check');
  expect(unpacked.code).toBe(1);
  expect(unpacked.stdout).toContain('dist/grand-voyage.muqun-theme is missing');
  expect(unpacked.stdout).toContain('muqun-theme pack grand-voyage');

  // A bare id names src/<id>, for pack and for validate alike.
  const pack = runIn(repo, 'pack', 'grand-voyage');
  expect(pack.code).toBe(0);
  expect(pack.stdout).toContain('packed dist/grand-voyage.muqun-theme');
  expect(existsSync(join(repo, 'dist', 'grand-voyage.muqun-theme'))).toBe(true);
  expect(runIn(repo, 'validate', 'grand-voyage').code).toBe(0);

  // A new package makes the catalogue stale until index is run again.
  const outdated = runIn(repo, 'check');
  expect(outdated.code).toBe(1);
  expect(outdated.stdout).toContain('index.json does not match dist/');
  expect(runIn(repo, 'index').stdout).toContain('wrote index.json (1 theme(s))');
  const catalogue = JSON.parse(readFileSync(join(repo, 'index.json'), 'utf8'));
  expect(catalogue.themes).toHaveLength(1);
  expect(catalogue.themes[0]).toMatchObject({
    id: 'grand-voyage',
    version: '1.0.0',
    package: 'dist/grand-voyage.muqun-theme',
    assets: 14,
  });
  expect(catalogue.themes[0].sha256).toMatch(/^[0-9a-f]{64}$/);

  const agreed = runIn(repo, 'check');
  expect(agreed.code).toBe(0);
  expect(agreed.stdout).toContain('check ok');
  expect(agreed.stdout).toContain('1 theme(s)');

  // The repository can list itself from its own catalogue, offline.
  const listed = runIn(repo, 'list', '--from', 'index.json');
  expect(listed.code).toBe(0);
  expect(listed.stdout).toContain('grand-voyage');
  expect(listed.stdout).toContain('1 theme(s)  page 1/1');

  // Editing the source without repacking is caught by the version it carries.
  const manifestFile = join(repo, 'src', 'grand-voyage', 'theme.json');
  writeFileSync(manifestFile, readFileSync(manifestFile, 'utf8').replace('"1.0.0"', '"1.0.1"'));
  const stale = runIn(repo, 'check');
  expect(stale.code).toBe(1);
  expect(stale.stdout).toContain('is 1.0.0 but src/grand-voyage is 1.0.1');

  // A package with no source is refused too.
  writeFileSync(join(repo, 'dist', 'orphan.muqun-theme'), readFileSync(join(repo, 'dist', 'grand-voyage.muqun-theme')));
  expect(runIn(repo, 'check').stdout).toContain('dist/orphan.muqun-theme');
  expect(runIn(repo, 'check').stdout).toContain('has no source in src/orphan/');
});

test('a pull request carries only sources: check --sources proves they pack, and build makes dist/ from them', () => {
  const repo = scratch();
  mkdirSync(join(repo, 'src'));
  mkdirSync(join(repo, 'dist'));
  expect(runIn(repo, 'init', 'amber-dusk').code).toBe(0);
  expect(runIn(repo, 'init', 'blue-harbor').code).toBe(0);

  // No dist/, no index.json, and that is fine for a source-only check.
  const sources = runIn(repo, 'check', '--sources');
  expect(sources.code).toBe(0);
  expect(sources.stdout).toContain('src/amber-dusk');
  expect(sources.stdout).toContain('packs to');
  expect(sources.stdout).not.toContain('index.json');
  expect(sources.stdout).toContain('check ok');

  // A source that cannot pack fails it, with pack's own reason.
  const manifestFile = join(repo, 'src', 'blue-harbor', 'theme.json');
  const manifest = JSON.parse(readFileSync(manifestFile, 'utf8'));
  manifest.assets['shell-light'].path = 'assets/nowhere.png';
  writeFileSync(manifestFile, JSON.stringify(manifest));
  const broken = runIn(repo, 'check', '--sources');
  expect(broken.code).toBe(1);
  expect(broken.stdout).toContain('nowhere.png');
  expect(runIn(repo, 'build').code).toBe(1);
  expect(existsSync(join(repo, 'index.json'))).toBe(false);

  // Fixed, build packs everything and writes the catalogue; full check agrees.
  manifest.assets['shell-light'].path = 'assets/shell-light.png';
  writeFileSync(manifestFile, JSON.stringify(manifest));
  const built = runIn(repo, 'build');
  expect(built.code).toBe(0);
  expect(built.stdout).toContain('packed dist/amber-dusk.muqun-theme');
  expect(built.stdout).toContain('packed dist/blue-harbor.muqun-theme');
  expect(built.stdout).toContain('built 2 theme(s)');
  expect(JSON.parse(readFileSync(join(repo, 'index.json'), 'utf8')).themes.map((t: { id: string }) => t.id)).toEqual([
    'amber-dusk',
    'blue-harbor',
  ]);
  expect(runIn(repo, 'check').code).toBe(0);

  // dist/ mirrors src/: a removed source takes its package with it.
  rmSync(join(repo, 'src', 'blue-harbor'), { recursive: true, force: true });
  const rebuilt = runIn(repo, 'build');
  expect(rebuilt.code).toBe(0);
  expect(rebuilt.stdout).toContain('removed dist/blue-harbor.muqun-theme');
  expect(existsSync(join(repo, 'dist', 'blue-harbor.muqun-theme'))).toBe(false);
  expect(JSON.parse(readFileSync(join(repo, 'index.json'), 'utf8')).themes).toHaveLength(1);
  expect(runIn(repo, 'check').code).toBe(0);
});

test('outside a repository, init and pack default beside the author', () => {
  const dir = scratch();
  const init = runIn(dir, 'init', 'grand-voyage');
  expect(init.code).toBe(0);
  expect(existsSync(join(dir, 'grand-voyage', 'theme.json'))).toBe(true);
  const pack = runIn(dir, 'pack', 'grand-voyage');
  expect(pack.code).toBe(0);
  expect(existsSync(join(dir, 'grand-voyage.muqun-theme'))).toBe(true);
});

test('check refuses a directory that is not laid out as a themes repository', () => {
  const dir = scratch();
  mkdirSync(join(dir, 'src'));
  const result = runIn(dir, 'check');
  expect(result.code).toBe(1);
  expect(result.stderr).toContain('not a themes repository');
});

test('skill prints the vendored skill byte for byte, writes it, and check notices drift', () => {
  const expected = readFileSync(SKILL_FILE, 'utf8');
  expect(run('skill').stdout).toBe(expected);

  const repo = scratch();
  mkdirSync(join(repo, 'src'));
  mkdirSync(join(repo, 'dist'));
  expect(runIn(repo, 'index').code).toBe(0);
  const wrote = runIn(repo, 'skill', '--out', 'skills/muqun-theme/SKILL.md');
  expect(wrote.code).toBe(0);
  expect(readFileSync(join(repo, 'skills', 'muqun-theme', 'SKILL.md'), 'utf8')).toBe(expected);
  expect(runIn(repo, 'check').stdout).toContain('matches this CLI');

  // Drift is a warning: it misinforms an agent, but it breaks no theme.
  writeFileSync(join(repo, 'skills', 'muqun-theme', 'SKILL.md'), expected + '\nlocal edit\n');
  const drifted = runIn(repo, 'check');
  expect(drifted.code).toBe(0);
  expect(drifted.stdout).toContain('differs from the skill this CLI carries');
  expect(drifted.stdout).toContain('muqun-theme skill --out skills/muqun-theme/SKILL.md');
});

test('list searches and pages a catalogue, and --json is the same page as data', () => {
  const dir = scratch();
  const entry = (id: string, extra: Record<string, unknown> = {}) => ({
    id,
    name: id.replace(/-/g, ' '),
    version: '1.0.0',
    package: 'dist/' + id + '.muqun-theme',
    bytes: 1024,
    sha256: 'f'.repeat(64),
    assets: 3,
    ...extra,
  });
  const catalogue = {
    format: 'muqun-themes-index',
    themes: [
      entry('amber-dusk', { tags: ['warm', 'dark'], author: 'Ada' }),
      entry('blue-harbor', { description: 'Cold light over the water' }),
      entry('grand-voyage', { tags: ['warm', 'sea'] }),
    ],
  };
  const file = join(dir, 'index.json');
  writeFileSync(file, JSON.stringify(catalogue));

  const first = runIn(dir, 'list', '--from', 'index.json', '--per-page', '2');
  expect(first.code).toBe(0);
  expect(first.stdout).toContain('3 theme(s)  page 1/2');
  expect(first.stdout).toContain('amber-dusk');
  expect(first.stdout).toContain('blue-harbor');
  expect(first.stdout).not.toContain('grand-voyage');
  expect(first.stdout).toContain('next: muqun-theme list --page 2');

  const second = runIn(dir, 'list', '--from', 'index.json', '--per-page', '2', '--page', '2');
  expect(second.code).toBe(0);
  expect(second.stdout).toContain('grand-voyage');
  expect(second.stdout).not.toContain('amber-dusk');

  // Past the end is a mistake, and says so.
  expect(runIn(dir, 'list', '--from', 'index.json', '--per-page', '2', '--page', '3').code).toBe(1);

  // Search covers tags, author and description, case-insensitively.
  const warm = runIn(dir, 'list', '--from', 'index.json', '--search', 'WARM');
  expect(warm.stdout).toContain('2 theme(s) matching "WARM"');
  expect(warm.stdout).not.toContain('blue-harbor');
  expect(runIn(dir, 'list', '--from', 'index.json', '--search', 'ada').stdout).toContain('amber-dusk');
  expect(runIn(dir, 'list', '--from', 'index.json', '--search', 'water').stdout).toContain('blue-harbor');
  const none = runIn(dir, 'list', '--from', 'index.json', '--search', 'zzz');
  expect(none.code).toBe(0);
  expect(none.stdout).toContain('no themes match "zzz"');

  const json = runIn(dir, 'list', '--from', 'index.json', '--search', 'sea', '--json');
  expect(json.code).toBe(0);
  const page = JSON.parse(json.stdout);
  expect(page.matched).toBe(1);
  expect(page.total).toBe(3);
  expect(page.entries[0].id).toBe('grand-voyage');

  // Something that is not a catalogue is refused with a sentence.
  writeFileSync(file, JSON.stringify({ hello: 'world' }));
  const refused = runIn(dir, 'list', '--from', 'index.json');
  expect(refused.code).toBe(1);
  expect(refused.stderr).toContain('Not a themes index');
});
