import { zlibSync } from 'fflate';

/**
 * Solid-colour PNGs, generated rather than shipped.
 *
 * `init` has to write artwork for every decoration slot, and the alternative to
 * generating it is committing a dozen binary fixtures to this repository --
 * files nobody can review in a diff, which exist only to be overwritten. A PNG
 * is a header, a zlib stream and a CRC per chunk, and `fflate` is already a
 * dependency for the ZIP layer, so the whole encoder is the few dozen lines
 * below.
 *
 * These are deliberately flat tints. A placeholder that looks like art is a
 * placeholder somebody ships by accident.
 */

const SIGNATURE = [137, 80, 78, 71, 13, 10, 26, 10];

/**
 * The marker that makes a placeholder recognisable after the fact.
 *
 * `tEXt` is an ancillary PNG chunk, so every decoder ignores it and the theme
 * image inspector accepts it. Detecting placeholders by their pixels would mean
 * guessing -- a flat tint is a legitimate thing to draw on purpose -- whereas a
 * marker is a fact the generator wrote down. It survives packing untouched,
 * because the ZIP layer copies asset bytes verbatim.
 */
const PLACEHOLDER_KEYWORD = 'muqun-theme';
const PLACEHOLDER_TEXT = 'placeholder artwork generated by muqun-theme init';

const crcTable = Uint32Array.from({ length: 256 }, (_, value) => {
  let crc = value;
  for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  return crc >>> 0;
});

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) crc = crcTable[(crc ^ byte) & 255] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Uint8Array): Uint8Array {
  const body = new Uint8Array(4 + data.length);
  for (let i = 0; i < 4; i++) body[i] = type.charCodeAt(i);
  body.set(data, 4);
  const out = new Uint8Array(body.length + 8);
  const view = new DataView(out.buffer);
  view.setUint32(0, data.length);
  out.set(body, 4);
  view.setUint32(out.length - 4, crc32(body));
  return out;
}

/** `#RGB`, `#RRGGBB` or `#RRGGBBAA` to four 0-255 channels. */
export function parseHexColor(hex: string): [number, number, number, number] {
  const value = hex.replace('#', '');
  const expand = value.length === 3 ? [...value].map((c) => c + c).join('') : value;
  if (!/^[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/.test(expand))
    throw new Error(`Not a hex colour: ${hex}`);
  const byte = (at: number) => Number.parseInt(expand.slice(at, at + 2), 16);
  return [byte(0), byte(2), byte(4), expand.length === 8 ? byte(6) : 255];
}

/**
 * An 8-bit RGBA PNG of one colour.
 *
 * Every scanline is a zero filter byte followed by the row, which is what the
 * spec calls filter type None. Uniform data, so DEFLATE reduces even a
 * full-screen image to a couple of kilobytes.
 */
export function solidPng(
  width: number,
  height: number,
  color: string,
  options: { placeholder?: boolean } = {}
): Uint8Array {
  if (!Number.isInteger(width) || !Number.isInteger(height) || width < 1 || height < 1)
    throw new Error('PNG dimensions must be positive integers');
  const [r, g, b, a] = parseHexColor(color);

  const stride = width * 4;
  const raw = new Uint8Array((stride + 1) * height);
  const row = new Uint8Array(stride);
  for (let x = 0; x < width; x++) row.set([r, g, b, a], x * 4);
  for (let y = 0; y < height; y++) raw.set(row, y * (stride + 1) + 1);

  const header = new Uint8Array(13);
  const headerView = new DataView(header.buffer);
  headerView.setUint32(0, width);
  headerView.setUint32(4, height);
  header.set([8, 6, 0, 0, 0], 8); // depth 8, RGBA, deflate, filter 0, non-interlaced

  const parts = [new Uint8Array(SIGNATURE), chunk('IHDR', header)];
  if (options.placeholder !== false) {
    // Before IDAT: the inspector treats any chunk after the image data as
    // trailing, and a keyword/NUL/text triple is the whole of a tEXt payload.
    const text = `${PLACEHOLDER_KEYWORD}\0${PLACEHOLDER_TEXT}`;
    parts.push(chunk('tEXt', Uint8Array.from(text, (c) => c.charCodeAt(0) & 0xff)));
  }
  parts.push(chunk('IDAT', zlibSync(raw, { level: 9 })), chunk('IEND', new Uint8Array(0)));

  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const png = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    png.set(part, offset);
    offset += part.length;
  }
  return png;
}

/**
 * Whether these bytes are artwork `init` wrote, still unreplaced.
 *
 * Scans for the tEXt marker without decoding. Deliberately a substring search
 * over the whole file rather than a chunk walk: a real drawing that happens to
 * contain this exact string is not a case worth engineering against, and the
 * consequence of a false positive is one warning.
 */
export function isPlaceholderImage(bytes: Uint8Array): boolean {
  const needle = Uint8Array.from(PLACEHOLDER_KEYWORD, (c) => c.charCodeAt(0));
  outer: for (let i = 0; i + needle.length <= bytes.length; i++) {
    for (let j = 0; j < needle.length; j++) if (bytes[i + j] !== needle[j]) continue outer;
    // The keyword is followed by NUL then the text, which is what separates the
    // marker from the same word appearing in, say, an embedded colour profile.
    const after = i + needle.length;
    if (bytes[after] === 0) return true;
  }
  return false;
}
